# Generated by Django 6.1.2 on 2026-10-10 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LeaderboardSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categories", models.JSONField(blank=True, default=list)),
                ("corporations", models.JSONField(blank=True, default=list)),
                ("show_characters", models.BooleanField(default=True)),
                ("places", models.PositiveSmallIntegerField(default=25)),
                ("medals", models.BooleanField(default=True)),
            ],
            options={
                "permissions": [
                    (
                        "manage_leaderboard",
                        "Can choose the leaderboard's categories, corporations and medals",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Award",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("month", models.DateField(db_index=True)),
                ("category", models.CharField(max_length=30)),
                ("rank", models.PositiveSmallIntegerField()),
                ("score", models.FloatField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="leaderboard_awards",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-month", "category", "rank"],
                "unique_together": {("month", "category", "user")},
            },
        ),
    ]
