# Generated by Django 6.1.2 on 2026-10-10 13:27

import conduit.accounts.crypto
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("access", "0003_group_modes_leaders_rules"),
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamSpeakSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query_host", models.CharField(blank=True, max_length=200)),
                ("query_port", models.PositiveIntegerField(default=10011)),
                ("query_user", models.CharField(blank=True, max_length=100)),
                (
                    "query_password",
                    conduit.accounts.crypto.EncryptedTextField(blank=True, default=""),
                ),
                ("server_id", models.PositiveIntegerField(default=1)),
                ("public_host", models.CharField(blank=True, max_length=200)),
                ("public_port", models.PositiveIntegerField(default=9987)),
                ("server_name", models.CharField(blank=True, max_length=100)),
                (
                    "nickname_format",
                    models.CharField(
                        default="[{corp_ticker}] {character}", max_length=100
                    ),
                ),
                ("registered_sgid", models.PositiveIntegerField(default=0)),
                ("kick_without_access", models.BooleanField(default=False)),
                ("require_for_compliance", models.BooleanField(default=False)),
                ("allowlisted", models.BooleanField(default=False)),
                ("server_groups", models.JSONField(blank=True, default=list)),
                ("virtual_server_name", models.CharField(blank=True, max_length=100)),
                ("server_version", models.CharField(blank=True, max_length=100)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_full_sync", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "TeamSpeak settings",
            },
        ),
        migrations.CreateModel(
            name="TeamSpeakUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cldbid",
                    models.PositiveIntegerField(blank=True, null=True, unique=True),
                ),
                ("uid", models.CharField(blank=True, max_length=64)),
                ("nickname", models.CharField(blank=True, max_length=100)),
                ("privilege_key", models.CharField(blank=True, max_length=100)),
                ("verify_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("sync_error", models.CharField(blank=True, max_length=300)),
                ("groups", models.JSONField(blank=True, default=list)),
                ("last_connected_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="teamspeak",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["user_id"],
                "permissions": [
                    ("access_teamspeak", "Can link a TeamSpeak identity"),
                    (
                        "manage_teamspeak",
                        "Can set up the TeamSpeak server and its groups",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="GroupMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sgid", models.PositiveIntegerField()),
                ("sg_name", models.CharField(blank=True, max_length=100)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="auth.group",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="access.state",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("group__isnull", False), ("state__isnull", True)),
                            models.Q(("group__isnull", True), ("state__isnull", False)),
                            _connector="OR",
                        ),
                        name="teamspeak_mapping_group_or_state",
                    ),
                    models.UniqueConstraint(
                        fields=("group", "sgid"), name="teamspeak_unique_group_mapping"
                    ),
                    models.UniqueConstraint(
                        fields=("state", "sgid"), name="teamspeak_unique_state_mapping"
                    ),
                ],
            },
        ),
    ]
