# Generated by Django 6.1.2 on 2026-10-07 19:32

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sheet_killmails", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SrpSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "default_percent",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("100.00"), max_digits=5
                    ),
                ),
                ("covered_only", models.BooleanField(default=False)),
                ("max_age_days", models.PositiveIntegerField(default=30)),
                ("require_fleet", models.BooleanField(default=True)),
                ("corporations", models.JSONField(blank=True, default=list)),
                ("rules_text", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="ShipRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("group_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("name", models.CharField(max_length=200)),
                ("covered", models.BooleanField(default=True)),
                (
                    "payout",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("group_id__isnull", True), ("type_id__isnull", False)
                            ),
                            models.Q(
                                ("group_id__isnull", False), ("type_id__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="srp_rule_type_or_group",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SrpRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_id", models.BigIntegerField()),
                ("character_name", models.CharField(max_length=100)),
                ("fleet", models.CharField(blank=True, max_length=200)),
                ("fc", models.CharField(blank=True, max_length=100)),
                ("notes", models.TextField(blank=True)),
                (
                    "suggested",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "payout",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("paid", "Paid"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("decided_at", models.DateTimeField(blank=True, null=True)),
                ("decision_note", models.TextField(blank=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "decided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "killmail",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="srp_request",
                        to="sheet_killmails.killmail",
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="srp_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("review_requests", "Can approve and reject SRP requests"),
                    (
                        "pay_requests",
                        "Can see approved SRP requests and mark them paid",
                    ),
                    ("manage_srp", "Can change SRP rules and payouts"),
                ],
            },
        ),
    ]
