# Generated by Django 6.1.2 on 2026-10-07 20:44

import conduit_fleets.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0002_userpreferences"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FleetType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(default="#38bdf8", max_length=7)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Fleet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("notes", models.TextField(blank=True)),
                (
                    "started_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("esi_fleet_id", models.BigIntegerField(blank=True, null=True)),
                ("tracking", models.BooleanField(db_index=True, default=False)),
                ("last_tracked_at", models.DateTimeField(blank=True, null=True)),
                ("tracking_error", models.CharField(blank=True, max_length=300)),
                (
                    "link_code",
                    models.CharField(
                        default=conduit_fleets.models.new_link_code,
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("link_open", models.BooleanField(default=True)),
                ("link_expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fc",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tracking_character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.character",
                    ),
                ),
                (
                    "fleet_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fleets",
                        to="fleets.fleettype",
                    ),
                ),
            ],
            options={
                "ordering": ["-started_at"],
                "permissions": [
                    (
                        "run_fleets",
                        "Can start fleets, track them and hand out FAT links",
                    ),
                    (
                        "manage_fleets",
                        "Can edit and delete any fleet, its FATs and fleet types, and see everyone's attendance",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Fat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("character_id", models.BigIntegerField(db_index=True)),
                ("character_name", models.CharField(max_length=100)),
                ("ship_type_id", models.IntegerField(blank=True, null=True)),
                ("solar_system_id", models.IntegerField(blank=True, null=True)),
                (
                    "via",
                    models.CharField(
                        choices=[
                            ("esi", "In-game fleet"),
                            ("link", "FAT link"),
                            ("manual", "Added by the FC"),
                        ],
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "fleet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fats",
                        to="fleets.fleet",
                    ),
                ),
            ],
            options={
                "ordering": ["character_name"],
                "unique_together": {("fleet", "character_id")},
            },
        ),
    ]
