# Generated by Django 6.1.2 on 2026-10-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="fleet",
            name="motd",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="fleet",
            name="motd_error",
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name="fleet",
            name="motd_written",
            field=models.TextField(blank=True),
        ),
    ]
