# Generated by Django 6.1.2 on 2026-10-10 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fleets", "0002_fleet_motd"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fat",
            options={"ordering": ["-round", "character_name"]},
        ),
        migrations.AlterUniqueTogether(
            name="fat",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="fat",
            name="round",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="fleet",
            name="fat_round",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="fleet",
            name="round_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="fat",
            unique_together={("fleet", "character_id", "round")},
        ),
    ]
