# Generated by Django 6.1.2 on 2026-10-07 19:42

import conduit.accounts.crypto
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("access", "0003_group_modes_leaders_rules"),
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DiscordSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("client_id", models.CharField(blank=True, max_length=32)),
                (
                    "client_secret",
                    conduit.accounts.crypto.EncryptedTextField(blank=True, default=""),
                ),
                (
                    "bot_token",
                    conduit.accounts.crypto.EncryptedTextField(blank=True, default=""),
                ),
                ("guild_id", models.CharField(blank=True, max_length=32)),
                ("guild_name", models.CharField(blank=True, max_length=100)),
                (
                    "nickname_format",
                    models.CharField(
                        blank=True,
                        default="[{corp_ticker}] {character}",
                        max_length=100,
                    ),
                ),
                ("kick_without_access", models.BooleanField(default=False)),
                ("last_full_sync", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Discord settings",
            },
        ),
        migrations.CreateModel(
            name="DiscordAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("discord_id", models.CharField(max_length=32, unique=True)),
                ("username", models.CharField(max_length=100)),
                ("avatar_url", models.CharField(blank=True, max_length=300)),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                ("sync_error", models.CharField(blank=True, max_length=300)),
                ("roles", models.JSONField(blank=True, default=list)),
                ("nickname", models.CharField(blank=True, max_length=32)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="discord",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["username"],
                "permissions": [
                    (
                        "access_discord",
                        "Can link a Discord account and join the server",
                    ),
                    ("manage_discord", "Can set up the Discord server and its roles"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RoleMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_id", models.CharField(max_length=32)),
                ("role_name", models.CharField(blank=True, max_length=100)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="auth.group",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="access.state",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("group__isnull", False), ("state__isnull", True)),
                            models.Q(("group__isnull", True), ("state__isnull", False)),
                            _connector="OR",
                        ),
                        name="discord_mapping_group_or_state",
                    ),
                    models.UniqueConstraint(
                        fields=("group", "role_id"), name="discord_unique_group_role"
                    ),
                    models.UniqueConstraint(
                        fields=("state", "role_id"), name="discord_unique_state_role"
                    ),
                ],
            },
        ),
    ]
