# Generated by Django 6.1.2 on 2026-10-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discord", "0002_default_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="discordaccount",
            name="on_server",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="discordsettings",
            name="require_for_compliance",
            field=models.BooleanField(default=False),
        ),
    ]
