# Generated by Django 6.1.2 on 2026-10-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("announcements", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="announcement",
            name="on_landing",
            field=models.BooleanField(default=True),
        ),
    ]
