# Generated by Django 6.1.2 on 2026-10-10 06:18

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("access", "0003_group_modes_leaders_rules"),
        ("accounts", "0004_more_themes"),
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemPrice",
            fields=[
                ("type_id", models.IntegerField(primary_key=True, serialize=False)),
                (
                    "buy",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                (
                    "sell",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("updated_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("solar_system_id", models.IntegerField()),
                ("structure_id", models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="PriceHistory",
            fields=[
                ("type_id", models.IntegerField(primary_key=True, serialize=False)),
                ("region_id", models.IntegerField()),
                ("days", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="BuybackSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "price_source",
                    models.CharField(
                        choices=[
                            ("esi", "ESI"),
                            ("fuzzwork", "Fuzzwork"),
                            ("janice", "Janice"),
                        ],
                        default="esi",
                        max_length=10,
                    ),
                ),
                ("hub_id", models.BigIntegerField(default=60003760)),
                ("hub_name", models.CharField(default="Jita 4-4", max_length=100)),
                ("instant_prices", models.BooleanField(default=False)),
                ("janice_api_key", models.CharField(blank=True, max_length=100)),
                ("market_pulled_at", models.DateTimeField(blank=True, null=True)),
                ("market_note", models.CharField(blank=True, max_length=300)),
                ("guard_enabled", models.BooleanField(default=True)),
                (
                    "guard_threshold",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("20"), max_digits=6
                    ),
                ),
                ("guard_days", models.PositiveSmallIntegerField(default=7)),
                ("guard_min_days", models.PositiveSmallIntegerField(default=5)),
                ("guard_both_ways", models.BooleanField(default=False)),
                ("price_max_age_hours", models.PositiveIntegerField(default=24)),
                ("tracking_prefix", models.CharField(default="bb-", max_length=20)),
                ("unlinked_purge_hours", models.PositiveIntegerField(default=48)),
                ("reject_disallowed", models.BooleanField(default=False)),
                ("restrict_quotes", models.BooleanField(default=True)),
                (
                    "esi_character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.character",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_corporation", models.BooleanField(default=True)),
                ("expiration_days", models.PositiveSmallIntegerField(default=14)),
                (
                    "price_type",
                    models.CharField(
                        choices=[("buy", "Buy"), ("sell", "Sell"), ("split", "Split")],
                        default="buy",
                        max_length=5,
                    ),
                ),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("10"), max_digits=5
                    ),
                ),
                (
                    "hauling_fuel_cost",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=12
                    ),
                ),
                (
                    "price_density_threshold",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=16
                    ),
                ),
                (
                    "price_density_tax",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=5
                    ),
                ),
                ("compressed_volume", models.BooleanField(default=False)),
                ("allow_all_items", models.BooleanField(default=True)),
                ("use_raw", models.BooleanField(default=True)),
                ("use_compressed", models.BooleanField(default=True)),
                ("use_refined", models.BooleanField(default=True)),
                (
                    "refining_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("80"), max_digits=5
                    ),
                ),
                ("allow_unpacked", models.BooleanField(default=False)),
                ("blue_loot_npc", models.BooleanField(default=False)),
                ("red_loot_npc", models.BooleanField(default=False)),
                ("t1_refined", models.BooleanField(default=False)),
                (
                    "t1_refining_rate",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("55"), max_digits=5
                    ),
                ),
                ("public", models.BooleanField(default=False)),
                ("notify_managers", models.BooleanField(default=True)),
                (
                    "wallet_division",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("tracking_prefix", models.CharField(blank=True, max_length=20)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="auth.group"
                    ),
                ),
                (
                    "locations",
                    models.ManyToManyField(
                        related_name="programs", to="buyback.location"
                    ),
                ),
                (
                    "managers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="buyback_programs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="accounts.character",
                    ),
                ),
                (
                    "states",
                    models.ManyToManyField(
                        blank=True, related_name="+", to="access.state"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "permissions": [
                    (
                        "view_leaderboard",
                        "Can see who sold the most to the buyback programs they use",
                    ),
                    (
                        "manage_programs",
                        "Can create buyback programs and run the ones they manage",
                    ),
                    (
                        "view_all_statistics",
                        "Can see the contracts and statistics of every buyback program",
                    ),
                    (
                        "manage_all_programs",
                        "Can run every buyback program and change buyback prices",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Quote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tracking_number", models.CharField(max_length=40, unique=True)),
                ("lines", models.JSONField(default=list)),
                ("value", models.DecimalField(decimal_places=2, max_digits=20)),
                ("volume", models.FloatField(default=0)),
                ("flagged", models.BooleanField(default=False)),
                ("public", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quotes",
                        to="buyback.program",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="buyback_quotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Contract",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contract_id", models.BigIntegerField(unique=True)),
                ("owner_id", models.BigIntegerField(db_index=True)),
                ("issuer_id", models.BigIntegerField()),
                ("issuer_corporation_id", models.BigIntegerField(null=True)),
                ("assignee_id", models.BigIntegerField()),
                ("for_corporation", models.BooleanField(default=False)),
                ("title", models.CharField(blank=True, max_length=200)),
                ("status", models.CharField(db_index=True, max_length=30)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=20
                    ),
                ),
                ("volume", models.FloatField(null=True)),
                ("start_location_id", models.BigIntegerField(null=True)),
                ("date_issued", models.DateTimeField(db_index=True)),
                ("date_expired", models.DateTimeField(null=True)),
                ("date_completed", models.DateTimeField(null=True)),
                ("items", models.JSONField(default=None, null=True)),
                ("problems", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "program",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contracts",
                        to="buyback.program",
                    ),
                ),
                (
                    "quote",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="contracts",
                        to="buyback.quote",
                    ),
                ),
            ],
            options={
                "ordering": ["-date_issued"],
            },
        ),
        migrations.CreateModel(
            name="ItemRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_id", models.IntegerField()),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                ("disallowed", models.BooleanField(default=False)),
                (
                    "static_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=20, null=True
                    ),
                ),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="item_rules",
                        to="buyback.program",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("program", "type_id"), name="buyback_item_rule_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="WatchRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("type_id", models.IntegerField(blank=True, null=True)),
                ("group_id", models.IntegerField(blank=True, null=True)),
                (
                    "program",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="watch_rules",
                        to="buyback.program",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("group_id__isnull", True), ("type_id__isnull", False)
                            ),
                            models.Q(
                                ("group_id__isnull", False), ("type_id__isnull", True)
                            ),
                            _connector="OR",
                        ),
                        name="buyback_watch_type_or_group",
                    )
                ],
            },
        ),
    ]
