# Generated by Django 6.1.2 on 2026-10-10 07:14

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buyback", "0002_program_markets"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("market_group_id", models.IntegerField()),
                (
                    "tax",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0"), max_digits=6
                    ),
                ),
                ("disallowed", models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="watchrule",
            name="buyback_watch_type_or_group",
        ),
        migrations.AddField(
            model_name="watchrule",
            name="market_group_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="watchrule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("group_id__isnull", True),
                        ("market_group_id__isnull", True),
                        ("type_id__isnull", False),
                    ),
                    models.Q(
                        ("group_id__isnull", False),
                        ("market_group_id__isnull", True),
                        ("type_id__isnull", True),
                    ),
                    models.Q(
                        ("group_id__isnull", True),
                        ("market_group_id__isnull", False),
                        ("type_id__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="buyback_watch_one_target",
            ),
        ),
        migrations.AddField(
            model_name="grouprule",
            name="program",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_rules",
                to="buyback.program",
            ),
        ),
        migrations.AddConstraint(
            model_name="grouprule",
            constraint=models.UniqueConstraint(
                fields=("program", "market_group_id"), name="buyback_group_rule_unique"
            ),
        ),
    ]
