# Generated by Django 6.1.2 on 2026-10-10 12:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("access", "0003_group_modes_leaders_rules"),
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MumbleSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("host", models.CharField(blank=True, max_length=200)),
                ("port", models.PositiveIntegerField(default=64738)),
                ("server_name", models.CharField(blank=True, max_length=100)),
                (
                    "username_format",
                    models.CharField(default="{character}", max_length=100),
                ),
                (
                    "display_format",
                    models.CharField(
                        default="[{corp_ticker}] {character}", max_length=100
                    ),
                ),
                ("allow_cert_auth", models.BooleanField(default=True)),
                ("temp_enabled", models.BooleanField(default=True)),
                ("temp_group", models.CharField(default="temp", max_length=50)),
                (
                    "temp_display_format",
                    models.CharField(default="[TEMP] {name}", max_length=100),
                ),
                ("temp_max_hours", models.PositiveIntegerField(default=48)),
                ("authenticator_seen_at", models.DateTimeField(blank=True, null=True)),
                ("authenticator_version", models.CharField(blank=True, max_length=40)),
            ],
            options={
                "verbose_name_plural": "Mumble settings",
            },
        ),
        migrations.CreateModel(
            name="MumbleUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=64, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("password_hash", models.CharField(max_length=128)),
                ("cert_hash", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "password_changed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("groups", models.JSONField(blank=True, default=list)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mumble",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["username"],
                "permissions": [
                    ("access_mumble", "Can have a Mumble account"),
                    ("create_temp_links", "Can hand out temporary Mumble access links"),
                    (
                        "manage_mumble",
                        "Can set up the Mumble server, its groups and accounts",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TempLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=48, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField()),
                ("max_uses", models.PositiveIntegerField(default=0)),
                ("groups", models.JSONField(blank=True, default=list)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TempUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=64, unique=True)),
                ("display_name", models.CharField(max_length=100)),
                ("password_hash", models.CharField(max_length=128)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("expires_at", models.DateTimeField()),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="mumble.templink",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="GroupMapping",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mumble_group", models.CharField(max_length=50)),
                (
                    "group",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="auth.group",
                    ),
                ),
                (
                    "state",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="access.state",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("group__isnull", False), ("state__isnull", True)),
                            models.Q(("group__isnull", True), ("state__isnull", False)),
                            _connector="OR",
                        ),
                        name="mumble_mapping_group_or_state",
                    ),
                    models.UniqueConstraint(
                        fields=("group", "mumble_group"),
                        name="mumble_unique_group_mapping",
                    ),
                    models.UniqueConstraint(
                        fields=("state", "mumble_group"),
                        name="mumble_unique_state_mapping",
                    ),
                ],
            },
        ),
    ]
