# Generated by Django 6.1.2 on 2026-10-07 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctrine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("icon_type_id", models.IntegerField(blank=True, null=True)),
                ("order", models.IntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-active", "order", "name"],
                "permissions": [
                    ("manage_doctrines", "Can create and edit doctrines and fits"),
                    ("view_readiness", "Can see who can fly each doctrine"),
                ],
            },
        ),
        migrations.CreateModel(
            name="Fit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("ship_type_id", models.IntegerField()),
                ("items", models.JSONField(default=list)),
                ("role", models.CharField(blank=True, max_length=40)),
                ("notes", models.TextField(blank=True)),
                ("recommended", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DoctrineFit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order", models.IntegerField(default=0)),
                (
                    "doctrine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="doctrines.doctrine",
                    ),
                ),
                (
                    "fit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entries",
                        to="doctrines.fit",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "pk"],
                "unique_together": {("doctrine", "fit")},
            },
        ),
        migrations.AddField(
            model_name="doctrine",
            name="fits",
            field=models.ManyToManyField(
                related_name="doctrines",
                through="doctrines.DoctrineFit",
                to="doctrines.fit",
            ),
        ),
    ]
