# Generated by Django 6.1.2 on 2026-10-10 12:33

import conduit_timers.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("sde", "0005_materials_and_compression"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TimerSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_minutes",
                    models.JSONField(
                        blank=True, default=conduit_timers.models.default_reminders
                    ),
                ),
                ("import_structures", models.BooleanField(default=True)),
                ("import_notifications", models.BooleanField(default=True)),
                ("keep_days", models.PositiveSmallIntegerField(default=14)),
                (
                    "notifications_seen_until",
                    models.DateTimeField(blank=True, null=True),
                ),
            ],
            options={
                "permissions": [
                    (
                        "manage_timers",
                        "Can add, edit and delete timers and change the timer settings",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Timer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("structure_type", models.CharField(blank=True, max_length=60)),
                ("type_id", models.IntegerField(blank=True, null=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("armor", "Armor"),
                            ("hull", "Hull"),
                            ("anchoring", "Anchoring"),
                            ("unanchoring", "Unanchoring"),
                            ("sov", "Sovereignty"),
                            ("moon", "Moon extraction"),
                            ("other", "Other"),
                        ],
                        default="armor",
                        max_length=12,
                    ),
                ),
                (
                    "side",
                    models.CharField(
                        choices=[
                            ("friendly", "Ours"),
                            ("hostile", "Hostile"),
                            ("neutral", "Neutral"),
                        ],
                        default="friendly",
                        max_length=10,
                    ),
                ),
                ("owner", models.CharField(blank=True, max_length=120)),
                ("ends_at", models.DateTimeField(db_index=True)),
                ("notes", models.TextField(blank=True)),
                ("important", models.BooleanField(default=False)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Added by hand"),
                            ("structure", "Corporation structure"),
                            ("notification", "In-game notification"),
                        ],
                        default="manual",
                        max_length=14,
                    ),
                ),
                (
                    "structure_id",
                    models.BigIntegerField(blank=True, db_index=True, null=True),
                ),
                ("reminded", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "going",
                    models.ManyToManyField(
                        blank=True, related_name="+", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "system",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="sde.solarsystem",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["ends_at"],
            },
        ),
    ]
