# Generated by Django 6.1.2 on 2026-10-10 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("timers", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="timer",
            name="ping",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="timer",
            name="ping_roles",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="timersettings",
            name="default_ping_roles",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
